[project]
authors = ["Paul Link <paullink65@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "book-library"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
tqdm = ">=4.67.1,<5"
python = ">=3.14.2,<3.15"
requests = ">=2.32.5,<3"
